### PR TITLE
Remove more useless 202612 code

### PR DESCRIPTION
**Pull request by Starmute**
These random keyimages should be removed immediately before block 202612 is mined.

### CODE REVIEW

**Comment by GoZippy** [comment]
what was the point of those key images?

**Comment by electroneumRepo** [comment]
This was included in our merged pull request #124.

We'd like to thank you for your helping in finding this issue.

**Comment by Starmute** [comment]
Hello Richard,

Thanks for merging this.

Please respond to my last email to you. It was sent on Monday and I have still received no response,

**Comment by lkelemen** [comment]
I downloaded it an running it. No problems so far...

**Pull request closed without merging**
