### PR TITLE
Use median timestamp if current time renders a block invalid

### PR DESCRIPTION
**Pull request by andrepatta**

### CODE REVIEW

**Comment by ThrownLemon** [comment]
Just an FYI I've had two reports so far that this patch may cause issues with the CastXMR software. Seems like the miner randomly gets banned by the pool for invalid shares.

Still trying to confirm more details and if this is related directly to this patch.

**Comment by andrepatta** [comment]
Hi @travis1234, thanks for letting us know that. Did you manage to confirm if the issue is related to this patch?

Thanks

**Comment by ThrownLemon** [comment]
I think it was an issue with the pool software and not this change specifically. @andrepatta

**Comment by electroneumRepo** [comment]
Included in #280

**Pull request closed without merging**
