### PR TITLE
monero block 202612 leftover fix

### PR DESCRIPTION
**Pull request by XzenTorXz**

### CODE REVIEW

**Comment by Daxorinator** [comment]
Nice work, now we just need it merged so that the chain will continue working.

**Comment by JoelIsMe** [comment]
after it has been merged, it needs a binary release for windows, mac and linux.

**Comment by JoelIsMe** [comment]
after the binary release, it needs a public news anouncement for updating the binary wallet/daemon
and a pools & cryptopia update on their servers.

**Comment by electroneumRepo** [comment]
This was included in our merged pull request #124.

We'd like to thank you for your helping in finding this issue.

**Pull request closed without merging**
