### PR TITLE
Hard-fork to Electroneum V2, changes in the hash algorithm, blocksize, fees and mempool livetime

### PR DESCRIPTION
**Pull request by andrepatta**

### CODE REVIEW

**Comment by cryptobender69** [comment]
Don't merge this, so many things missing. I mean cmon dude, atleast copy properly.

**Comment by Dwynr** [comment]
^this.

Submit a new pull request and I'm down to compile it and try it (testnet).

**Comment by andrepatta** [comment]
Will do. Thanks for pointing that out. I was running my testnet yesterday night and I noticed that I was missing something. I'll apply the changes as soon as I have some free time later today.

**Comment by Dwynr** [comment]
Cool! Share the details for your testnet and I will contribute some hashpower so we can properly test it.

(Maybe even setup a seperated testnet github?)

**Comment by cryptobender69** [comment]
I have patches in here if you don't want to copy paste.

https://github.com/cryptobender69/ASICCryptoNightVariantPatch/tree/master/monero

**Comment by andrelpg** [comment]
I'm closing this pull request as I'm currently creating another one with the changes suggested.

**Comment by andrepatta** [comment]
Patch has been updated with small fixes and optimizations from Monero's codebase

**Comment by cryptobender69** [comment]
Thanks @andrelpg !

**Comment by cryptobender69** [comment]
@Dwynr how do you test the ASIC change? What do you look for exactly?

**Comment by andrepatta** [comment]
@electroneumRepo @ChrisCharrison @DeanCole  I'm just wondering if you could help us in the setup of an official **testnet** environment and repo for the Electroneum project. 

The idea is to create a **electroneum-testnet** repo in which contributors could help on changes and once a Pull Request is merged in this new repo, latest version of deamon is deployed in the testnet server through Continuous Integration. This way we can assure that a PR goes through the testnet server/testing before going live in production.

Other suggestion and feedback are more than welcome.

Thanks!

**Comment by andrepatta** [comment]
Quick update: I've finished running all tests on my private testnet and the hardfork to the ASIC-Resistant hash is working fine.

**Comment by Dwynr** [comment]
Sounds great! Good work @andrelpg 

Now we just need the ETN Team to notice us :/

@electroneumRepo 
@DeanCole

**Comment by andrepatta** [comment]
Credits to @Dwynr regarding changes in blocksize and max ringsize.

**Comment by Starmute** [comment]
@andrelpg You MUST NOT upgrade to v6. v6 enforces ringCT which must not be allowed due to increase in tx size. You should use CryptoNightV7 but NOT other feature of V6.

**Comment by Starmute** [comment]
Please change the fork height to a higher value. 250000 is too short a deadline.

**Comment by andrepatta** [comment]
@Starmute The fork height still needs to be defined by Electroneum. I will change accordingly once I get a confirmed date.

**Comment by Dwynr** [comment]
@andrelpg I'd say we run all the codechanges on a testnet first.

**Comment by andrepatta** [comment]
@Dwynr I've been running a testnet on these changes already and the block reward/fees needs fine tuning due to ringct and mixin enforced in newer versions. I'm considering update to V5 for the sort term so we can sort out the issues with flood, empty blocks and ASICs asap. I'm still discussing with the team about these changes.

@Dwynr ,@Starmute (or anyone) Feel free to suggest changes and ideas.

**Comment by jeffreyscholz** [comment]
I second the idea to have an electroneum-testnet repo. I'd be happy to run a node on the testnet. In fact, I don't mind creating bots to send test-electroneum around on the testnet and log when something transactions start failing or something.

I don't know how other coins handle this, but is it also possible to fast forward into the future on the testnet (or maybe have a version of the testnet with short block times)? That way we can catch stuff like the 202612 bug and the 179840 bug before they happen.

If I'm spamming up this thread, please let me know and I'll delete this comment and open a separate ticket.

**Comment by Starmute** [comment]
You don’t need a separate repo to create a testnet.

**Comment by cryptobender69** [comment]
Patta, try creating a wallet using simplewallet with all these changes you made in this pull request and let me know if it works.

@andrepatta

**Comment by andrepatta** [comment]
@cryptobender69 Simplewallet is working fine on my testnet. 

Please let me know if you're facing any issues with your wallet.

**Comment by cryptobender69** [comment]
@andrepatta ok now it is working fine. Issue on my side. But I want to verify that the ASIC resistance is working. Could you please guide me on how did you go about verifying that?

**Comment by andrepatta** [comment]
@cryptobender69 Unfortunately, we don't have an ASIC to do the real testing. However, considering that this change was taken from Monero, a reasonable test would be to make sure that the code VARIANT1_1 and VARIANT1_2 (from slow-hash.c) are being executed when mining blocks.

**Comment by Dwynr** [comment]
Great work @andrepatta !

Maybe I can try to reach a friend of mine, he might know a guy with a FPGA (Baikal) who might rent it to me for a few minutes :)

**Comment by cryptobender69** [comment]
@andrepatta what would happen if you run the miner from the master branch on daemon of ASIC resistant branch?

**Comment by andrepatta** [comment]
@cryptobender69 Didn't really get your question, sorry.

**Comment by Dwynr** [comment]
@cryptobender69 I guess it would simply not work because of the different blocktemplate? I don't know if I get your question right though.

**Comment by cryptobender69** [comment]
I tried, it on my coin. the blocks generate wont sync with the seed servers and other nodes running newer version.

**Comment by cryptobender69** [comment]
@andrepatta 1 more -  delete line 1347 from slow-hash.c **VARIANT1_2**, I cannot steal your code if you have so many mistakes ;)

**Comment by felipe-vvoosh** [comment]
How long it will take for ETN to be ASIC Resistant? Will them wait the end of the coin?

**Pull request closed without merging**
