### PR TITLE
* Disable RingCT

### PR DESCRIPTION
**Pull request by DeanCole**

### CODE REVIEW

**Comment by ra-dave** [comment]
Why?

**Comment by electroneumRepo** [comment]
[Quote Taken From Blog Post](https://electroneum.com/2018/04/25/blockchain-update/)
> Disabling of RingCT & Mixin. RingCT was introduced by Monero whose main focus is privacy. Our main focus is bulk transactions for a mass audience, and thus we are disabling some of the privacy features of the blockchain. Disabling some privacy features means we can fit significantly more transactions into each block than with them enabled. This means less wait to get a transaction into a block and a leaner blockchain size. Wallets are still private as we will continue to use a new stealth wallet address for every blockchain transaction so there is still significantly more privacy than with Bitcoin or Ethereum, but considerably less privacy than with a privacy focused coin like Monero.

**Comment by ra-dave** [comment]
Well block 307500 was just mined a few hours ago and it's still showing Mixins > 1.  Was this left in?

**Comment by Unyxos** [comment]
It’s fixed to 1 I believe

**Pull request merged**
